jobs/urls.py
from django.conf.urls import include
from django.urls import path

from .views import index, post
from .api import v1 as api_v1


app_name = 'jobs'

urlpatterns = (
    path('', index, name='index'),
    path('api/', include(api_v1.urls)),
    path('post', post, name='post'),
)

pythonph/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

urlpatterns = (
    path('', include('landing.urls', namespace='landing')),
    path('', include('registration.urls', namespace='registration')),
    path('slack/', include('slack.urls', namespace='slack')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('admin/', admin.site.urls, name='admin'),
    path('markdownx/', include('markdownx.urls')),
)

registration/urls.py
from django.conf.urls import include
from django.urls import path

from .views import register


app_name = 'registration'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', register, name='register'),
]

jobs/models.py
from markdownx.models import MarkdownxField
from taggit.managers import TaggableManager

from django.contrib.auth.models import User
from django.db import models


class Company(models.Model):

    class Meta:
        verbose_name_plural = "companies"

    user = models.ForeignKey(
        User,
        related_name="companies",
        null=True,
        on_delete=models.SET_NULL,
    )

    name = models.CharField(max_length=255)
    profile = MarkdownxField()
    homepage = models.URLField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Job(models.Model):
    user = models.ForeignKey(
        User,
        related_name='jobs',
        on_delete=models.CASCADE,
    )
    company = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        related_name='jobs',
    )
    is_approved = models.BooleanField(default=False)
    is_sponsored = models.BooleanField(default=False)
    tags = TaggableManager()

    title = models.CharField(max_length=255)
    description = MarkdownxField()
    location = models.CharField(max_length=255)
    application_url = models.URLField(blank=True, null=True)
    application_email = models.EmailField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "{} - {}".format(self.company.name, self.title)

jobs/forms.py
from django.forms import ModelForm
from jobs.models import Company, Job


class CompanyForm(ModelForm):
    class Meta:
        model = Company
        exclude = ["user"]


class JobForm(ModelForm):
    class Meta:
        model = Job
        exclude = [
            "tags",
            "user",
            "company",
            "is_approved",
            "is_sponsored",
            "is_active",
        ]

jobs/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from .forms import CompanyForm, JobForm
from common.utils import notify_slack


def index(request):
    context = dict(api_version='v1')
    return render(request, 'jobs/index.html', context)


@login_required
def post(request):
    job_posted = False
    company = request.user.companies.first()

    if request.method == 'POST':
        company_form = CompanyForm(request.POST, instance=company)
        job_form = JobForm(request.POST)

        if company_form.is_valid() and job_form.is_valid():
            company = company_form.save(commit=False)
            company.user = request.user
            company.save()

            job = job_form.save(commit=False)
            job.user = request.user
            job.company = company
            job.save()
            job_posted = True
    else:
        company_form = CompanyForm(instance=company)
        job_form = JobForm()

    if job_posted:
        notify_slack(
            'New job posting: {}'.format(job.title),
            settings.SLACK_BOARD_CHANNEL
        )

    context = {
        'job_posted': job_posted,
        'company_form': company_form,
        'job_form': job_form,
    }
    return render(request, 'jobs/post.html', context)

jobs/templates/jobs/base.html
{% extends "base.html" %}
{% load staticfiles %}
{% load compress %}

{% block title %}Python.PH Jobs Board{% endblock %}
{% block description %}Python.PH Jobs Board{% endblock %}

{% block css %}
{{ block.super }}
{% compress css %}
<link rel="stylesheet" type="text/x-scss" href="{% static "jobs/scss/main.scss" %}">
{% endcompress %}
{% endblock %}

{% block content %}
<div class="header">
  <div class="title">
    <h1><a href="{% url "jobs:index" %}">
      Python.PH<br>
      <small>Jobs Board</small>
    </a></h1>
    <div class="ghbtns">
      <iframe
        src="https://ghbtns.com/github-btn.html?user=pythonph&repo=pythonph&type=watch&count=true"
        allowtransparency="true" frameborder="0" scrolling="0" width="95"
        height="20"></iframe>
      <iframe
        src="https://ghbtns.com/github-btn.html?user=pythonph&repo=pythonph&type=fork&count=true"
        allowtransparency="true" frameborder="0" scrolling="0" width="95"
        height="20"></iframe>
    </div>
  </div>
  <ul class="links">
    {% if user.is_authenticated %}
    <li><a class="button" href="{% url "jobs:post" %}">Post a Job</a></li>
    <li><a class="button" href="{% url "registration:logout" %}?next=/jobs/">Logout</a></li>
    {% else %}
    <li><a class="button" href="{% url "registration:login" %}?next=/jobs/">Login</a></li>
    <li><a class="button" href="{% url "registration:register" %}?next=/jobs/">Register</a></li>
    {% endif %}
  </ul>
  </ul>
</div>
{% block jobs_content %}{% endblock %}
<div class="footer">
  Made by the volunteers of <a href="https://python.ph/">Python.PH</a>
</div>
{% endblock %}

jobs/templates/jobs/index.html
{% extends "jobs/base.html" %}
{% load staticfiles %}
{% load compress %}

{% block jobs_content %}
<div id="jobs"></div>
{% endblock %}

{% block js %}
{{ block.super }}
<script>
  window.apiVersion = "{{ api_version|escapejs }}";
</script>
{% compress js %}
<script src="{% static "jobs/js/dist/main.js" %}"></script>
{% endcompress %}
{% endblock %}

jobs/templates/jobs/post.html
{% extends "jobs/base.html" %}

{% block jobs_content %}
<div class="post">

{% if job_posted %}
<h2>Job has been submitted for review</h2>
<p>
  We require approval before a job is listed.
  Check in after a day or two.
</p>
{% else %}
<form action="{% url "jobs:post" %}" method="post">
  <h2>Post a Job</h2>
  {% csrf_token %}
  <div class="company-form">
  <h3>Company</h3>
  {{ company_form.as_p }}
  </div>
  <div class="job-form">
  <h3>Job</h3>
  {{ job_form.as_p }}
  </div>
  <p class="submit">
    <button class="button" type="submit">
      Submit
    </button>
  </p>
</form>
{% endif %}

</div>
{% endblock %}